### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Kwiatjk** [mkuoppa/esphomeweatherstation#3]
Why do You use #rotations_per_sec = pulses/2/60 there are 2 magnes ? 

How will be if i have 3 magnes ?

#circ_m=0.09*2*3.14 = 0.5652
Is 2 pi * radius 
so speed should be 
speed = ( (pulses / pulse_peer_rotation) (2 pi * radius) )

why you use 1.18*

**Comment by mkuoppa** [comment]
1.18 is a calibration factor that I found out is working for my specific equipment.
