### ISSUE TITLE
Clarification on math formula and how to use.

### ISSUE THREAD

**Issue by jumper-d-1981** [mkuoppa/esphomeweatherstation#4]
The math is escaping me, also how to use it.
I have a wind speed sensor from spark fun, with a radius of .09m

Which seems to be what your example uses, but the output of the unchanged code reads too high.

I am trying to figure out how to properly calibrate this to display kph or mph, but first have to get proper yaml config for just the base output.

Any examples of working code would be appreciated.  I understand this repository is not used a lot, but would love it if an update could be provided because there are a lot of folks that seem to want to do a similar project in HA but there is no fully complete examples.

Thanks.

**Comment by mkuoppa** [comment]
Se comment in https://community.home-assistant.io/t/davis-1640-wind-gauge-calculations/327824/6
